name: XPBuy
main: com.bobjoejim.xpbuy.XPBuy
version: 2.7.1
author: Bobjoejim
description: Buy kits with your experience levels!
commands:
  xpbuy:
    description: Opens the XPBuy menu
    usage: /xpbuy
  xpb:
    description: Opens the XPBuy menu
    usage: /xpb
permissions:
  xpbuy.*:
    description: Gives access to all XPBuy commands
    deafult: op
    children:
      xpbuy.help: true
      xpbuy.list: true
      xpbuy.buy: true
      xpbuy.usesigns: true
      xpbuy.createsigns: true
      xpbuy.create: true
      xpbuy.remove: true
      xpbuy.edit: true
      xpbuy.giveperm: true
      xpbuy.delperm: true
      xpbuy.admin: true
      xpbuy.reload: true
  xpbuy.default:
    description: Gives access to the default XPBuy features
    default: false
    children:
      xpbuy.help: true
      xpbuy.list: true
      xpbuy.buy: true
      xpbuy.usesigns: true
    xpbuy.admin:
      description: Gives access to XPBuy admin commands
      default: op
      children:
        xpbuy.create: true
        xpbuy.remove: true
        xpbuy.edit: true
        xpbuy.createsigns: true
        xpbuy.giveperm: true
        xpbuy.delperm: true
        xpbuy.adminmode: true
        xpbuy.reload: true
  xpbuy.help:
    description: Allows you to display help
    default: false
  xpbuy.list:
    description: Allows you to list kits
    default: false
  xpbuy.buy:
    description: Allows you to buy a kit
    default: false
  xpbuy.usesigns:
    description: Allows you to use class signs
    default: false
  xpbuy.createsigns:
    description: Allows you to create class signs
    default: false
  xpbuy.create:
    description: Allows you to create kits in-game
    default: false
  xpbuy.remove:
    description: Allows you to remove kits in-game
    default: false
  xpbuy.edit:
    description: Allows you to edit kits in-game
    default: false
  xpbuy.giveperm:
    description: Allows you to give kit permissions to players
    default: false
  xpbuy.delperm:
    description: Allows you to delete kit permissions from players
    default: false
  xpbuy.adminmode:
    description: Allows admin access
    default: false
  xpbuy.reload:
    description: Allows you to reload
    default: op
